name: 🔧 Build -> Package 📦
on: [push, pull_request]

env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master

jobs:
  static-checks:
    name: 📊 Static Checks (clang-format, black format, file format)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            files=$(git diff-tree --no-commit-id --name-only -r HEAD^1..HEAD 2> /dev/null || true)
          elif [ "${{ github.event_name }}" == "push" -a "${{ github.event.forced }}" == "false" -a "${{ github.event.created }}" == "false" ]; then
            files=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }}..${{ github.event.after }} 2> /dev/null || true)
          fi
          files=$(echo "$files" | xargs -I {} sh -c 'echo "\"./{}\""' | tr '\n' ' ')
          echo "CHANGED_FILES=$files" >> $GITHUB_ENV

      - name: Style checks via pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ env.CHANGED_FILES }}

  build:
    runs-on: ${{ matrix.os }}
    name: 🔧 Build
    needs: static-checks
    strategy:
      fail-fast: false
      matrix:
        include:
          # Android
          - platform: android
            arch: 'x86_64'
            sconsflags: 'ANDROID_HOME='
            os: 'ubuntu-24.04'
            cache-name: android-x86_64
          - platform: android
            arch: 'arm64'
            sconsflags: 'ANDROID_HOME='
            os: 'ubuntu-24.04'
            cache-name: android-arm64

          # iOS
          #- platform: ios
          #  arch: 'x86_64'
          #  sconsflags: 'ios_simulator=true'
          #  os: 'macos-latest'
          #  cache-name: ios-x86_64-simulator
          - platform: ios
            arch: 'arm64'
            sconsflags: ''
            os: 'macos-latest'
            cache-name: ios-arm64

          # Linux
          - platform: linux
            arch: 'x86_32'
            buildroot: 'i686-godot-linux-gnu_sdk-buildroot'
            sconsflags: ''
            os: 'ubuntu-24.04'
            cache-name: linux-x86_32
          - platform: linux
            arch: 'x86_64'
            buildroot: 'x86_64-godot-linux-gnu_sdk-buildroot'
            sconsflags: ''
            os: 'ubuntu-24.04'
            cache-name: linux-x86_64
          - platform: linux
            arch: 'arm32'
            buildroot: 'arm-godot-linux-gnueabihf_sdk-buildroot'
            sconsflags: ''
            os: 'ubuntu-24.04'
            cache-name: linux-arm32
          - platform: linux
            arch: 'arm64'
            buildroot: 'aarch64-godot-linux-gnu_sdk-buildroot'
            sconsflags: ''
            os: 'ubuntu-24.04'
            cache-name: linux-arm64

          # macOS
          - platform: macos
            arch: 'universal'
            sconsflags: ''
            os: 'macos-latest'
            cache-name: macos-universal

          # Windows
          - platform: windows
            arch: 'x86_32'
            sconsflags: 'use_mingw=yes'
            os: 'ubuntu-24.04'
            msvc_arch: amd64_x86
            cache-name: win-x86_32
          - platform: windows
            arch: 'x86_64'
            sconsflags: 'use_mingw=yes'
            os: 'ubuntu-24.04'
            msvc_arch: amd64
            cache-name: win-x86_64

    env:
      SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
      SCONSFLAGS: ${{ matrix.sconsflags }} platform=${{ matrix.platform }} arch=${{ matrix.arch }} build_profile=build_profile.json --jobs=2

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Install Windows build dependencies
        if: ${{ matrix.platform == 'windows' }}
        run: |
          sudo apt-get update
          sudo apt-get install build-essential mingw-w64
          sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
          sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          dpkg -l | grep ii | grep mingw
          update-alternatives --get-selections | grep mingw

      - name: Install Linux build dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install build-essential gcc-multilib g++-multilib wget

      - name: Setup Linux buildroot toolchain cache
        if: ${{ matrix.platform == 'linux' }}
        uses: actions/cache@v4
        with:
          path: |
            ${{ matrix.buildroot }}.tar.bz2
          key: linux-${{ matrix.buildroot }}-buildroot

      - name: Android dependencies
        id: android-setup-ndk
        if: ${{ matrix.platform == 'android' }}
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
          add-to-path: true

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons

      - name: Setup Linux toolchains
        if: ${{ matrix.platform == 'linux' }}
        run: |
          if [ ! -f ${{ matrix.buildroot }}.tar.bz2 ]; then
            wget https://github.com/godotengine/buildroot/releases/download/godot-2023.08.x-4/${{ matrix.buildroot }}.tar.bz2
          fi
          tar -xjf ${{ matrix.buildroot }}.tar.bz2
          ${{ matrix.buildroot }}/relocate-sdk.sh
          rm ${{ matrix.buildroot }}/bin/cmake
          echo "$GITHUB_WORKSPACE/${{ matrix.buildroot }}/bin" >> $GITHUB_PATH
          echo "PKG_CONFIG=$GITHUB_WORKSPACE/${{ matrix.buildroot }}/share/pkgconfig/" >> $GITHUB_ENV

      - name: Print tools versions
        run: |
          python --version
          scons --version
          cmake --version

      - name: Compile Extension - template_debug - ${{ matrix.platform }} - ${{ matrix.arch }}
        env:
          ANDROID_NDK_ROOT: ${{ steps.android-setup-ndk.outputs.ndk-path }}
        run: |
          scons target=template_debug

      - name: Compile Extension - template_release - ${{ matrix.platform }} - ${{ matrix.arch }}
        env:
          ANDROID_NDK_ROOT: ${{ steps.android-setup-ndk.outputs.ndk-path }}
        run: |
          scons target=template_release

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            bin/
            !bin/thirdparty/

  package:
    name: 📦 Package
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Bundle licenses.
        run: |
          cp LICENSE artifacts/LICENSE.gdcurl
          cp thirdparty/curl/COPYING artifacts/LICENSE.curl
          cp thirdparty/openssl/LICENSE.txt artifacts/LICENSE.openssl
          cp thirdparty/mbedtls/LICENSE artifacts/LICENSE.mbedtls

      - name: Package artifacts for release
        env:
          DESTINATION: "release"
        run: |
          mkdir release

          NAME="gdcurl" ./misc/scripts/package_release.sh

          ls -R release

      - uses: actions/upload-artifact@v4
        with:
          name: godot-gdcurl
          path: release/godot-gdcurl.zip
